### ISSUE TITLE
Aspect ratio not preserved when full-screening image

### ISSUE THREAD

**Issue by mikenemat** [bp2008/blueirisviewer#1]
Hey there,

I'm having a strange new issue where clicking a camera to full-screen the image causes the picture to be stretched horizontally across the entire frame, but not vertically. Essentially the aspect ratio of the image is completely distorted.

Seems to be relatively new - maybe due to a recent blue iris update? I've been using your awesome app for years and just started seeing it now on both Windows 10 and OS X.

**Comment by bp2008** [comment]
If you are on Blue Iris 4.7.4.1 (the latest currently) then it is sending the wrong resolution of frames.  Should be fixed in the next Blue Iris update whenever that is.

**Comment by mikenemat** [comment]
That explains it! Thanks!

**Comment by bp2008** [comment]
Blue Iris 4.7.4.2 is still exhibiting the problem.  I guess wait for the next patch again ;)

**Comment by mikenemat** [comment]
Fixed in 4.7.4.3

**Comment by bp2008** [comment]
Yes it is
