### ISSUE TITLE
NO Issue, just a request

### ISSUE THREAD

**Issue by DCPDad** [bp2008/blueirisviewer#2]
Hi-
Been LOVING your cool lightweight BlueIrisViewer. Works like a charm.
Have you ever thought of making a tool to be able to watch bvr files?
Thanks again!
Dan

**Comment by bp2008** [comment]
I've certainly thought about it, but I always get stuck at the part where I don't know how to decode a bvr file.  I could ask the developer and maybe he would give me a format specification, but that is just creating more work for me. LOL.  I have enough projects right now ;)

**Comment by DCPDad** [comment]
Thx for the quick response. I completely understand. NO worries.
